"""Report generation module."""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
from datetime import datetime
from pathlib import Path
from ai import AIGenerator

class ReportGenerator:
    def __init__(self, memory):
        self.memory = memory
        self.ai_generator = AIGenerator()
    
    def generate_markdown(self, output_path: Path, include_raw: bool = False) -> str:
        findings = self.memory.get_findings()
        summary = self.memory.get_summary()
        risk_score = self.memory.calculate_risk_score()
        metadata = self.memory.metadata
        
        exec_summary = self.ai_generator.generate_executive_summary(
            findings, 
            metadata.target_url if metadata else "Unknown",
            risk_score
        ) if self.ai_generator.api_key else ""
        
        md = f"""# Vulnerability Assessment Report

**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}  
**Target:** {metadata.target_url if metadata else 'Unknown'}  
**Scan ID:** {self.memory.scan_id}  
**Status:** {metadata.status if metadata else 'Unknown'}

---

## Executive Summary

{exec_summary or self._basic_summary(findings, risk_score)}

---

## Risk Score: {risk_score:.1f}/10

### Severity Distribution

| Severity | Count |
|----------|-------|
| CRITICAL | {summary['by_severity'].get('CRITICAL', 0)} |
| HIGH | {summary['by_severity'].get('HIGH', 0)} |
| MEDIUM | {summary['by_severity'].get('MEDIUM', 0)} |
| LOW | {summary['by_severity'].get('LOW', 0)} |
| INFO | {summary['by_severity'].get('INFO', 0)} |
| **Total** | **{len(findings)}** |

---

## Findings

"""
        for i, finding in enumerate(sorted(findings, key=lambda x: self._severity_order(getattr(x, 'severity', 'INFO'))), 1):
            md += self._format_finding(finding, i)
        
        md += """

---

## Tools Executed

"""
        for tool, count in summary['by_tool'].items():
            md += f"- **{tool}**: {count} findings\n"
        
        md += f"""

---

## Recommendations

{self._generate_recommendations(findings)}

---
*Report generated by AI-Powered Vulnerability Scanner*
"""
        
        with open(output_path, "w") as f:
            f.write(md)
        
        return md
    
    def generate_json(self, output_path: Path) -> dict:
        findings = self.memory.get_findings()
        summary = self.memory.get_summary()
        risk_score = self.memory.calculate_risk_score()
        
        report = {
            "metadata": {
                "scan_id": self.memory.scan_id,
                "target_url": self.memory.metadata.target_url if self.memory.metadata else "Unknown",
                "generated_at": datetime.utcnow().isoformat(),
                "status": self.memory.metadata.status if self.memory.metadata else "Unknown"
            },
            "summary": {
                "total_findings": len(findings),
                "risk_score": risk_score,
                "by_severity": summary["by_severity"],
                "by_tool": summary["by_tool"]
            },
            "findings": [f.to_dict() if hasattr(f, 'to_dict') else f for f in findings]
        }
        
        with open(output_path, "w") as f:
            json.dump(report, f, indent=2)
        
        return report
    
    def generate_html(self, output_path: Path) -> str:
        findings = self.memory.get_findings()
        summary = self.memory.get_summary()
        risk_score = self.memory.calculate_risk_score()
        metadata = self.memory.metadata
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vulnerability Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; }}
        h1 {{ color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }}
        .meta {{ background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        .finding {{ border: 1px solid #ddd; border-radius: 5px; padding: 15px; margin: 10px 0; }}
        .finding-CRITICAL {{ border-left: 4px solid #dc3545; }}
        .finding-HIGH {{ border-left: 4px solid #fd7e14; }}
        .finding-MEDIUM {{ border-left: 4px solid #ffc107; }}
        .finding-LOW {{ border-left: 4px solid #20c997; }}
        .finding-INFO {{ border-left: 4px solid #17a2b8; }}
        .badge {{ display: inline-block; padding: 3px 8px; border-radius: 3px; color: white; font-size: 11px; font-weight: bold; }}
        .badge.CRITICAL {{ background: #dc3545; }}
        .badge.HIGH {{ background: #fd7e14; }}
        .badge.MEDIUM {{ background: #ffc107; color: #333; }}
        .badge.LOW {{ background: #20c997; }}
        .badge.INFO {{ background: #17a2b8; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Vulnerability Assessment Report</h1>
        <div class="meta">
            <strong>Target:</strong> {metadata.target_url if metadata else 'Unknown'}<br>
            <strong>Scan ID:</strong> {self.memory.scan_id}<br>
            <strong>Risk Score:</strong> {risk_score:.1f}/10
        </div>
        <h2>Findings ({len(findings)} total)</h2>
"""
        
        for finding in sorted(findings, key=lambda x: self._severity_order(getattr(x, 'severity', 'INFO'))):
            html += self._format_finding_html(finding)
        
        html += """
    </div>
</body>
</html>"""
        
        with open(output_path, "w") as f:
            f.write(html)
        
        return html
    
    def _format_finding(self, finding, index: int) -> str:
        name = getattr(finding, 'name', 'Unknown')
        severity = getattr(finding, 'severity', 'INFO')
        tool = getattr(finding, 'tool', 'Unknown')
        url = getattr(finding, 'url', '')
        desc = getattr(finding, 'description', '')
        
        return f"""### {index}. {name}

- **Severity:** {severity}
- **Tool:** {tool}
- **URL:** `{url}`

**Description:** {desc}

---
"""
    
    def _format_finding_html(self, finding) -> str:
        name = getattr(finding, 'name', 'Unknown')
        severity = getattr(finding, 'severity', 'INFO')
        tool = getattr(finding, 'tool', 'Unknown')
        url = getattr(finding, 'url', '')
        desc = getattr(finding, 'description', '')
        
        return f"""        <div class="finding finding-{severity}">
            <strong>{name}</strong> <span class="badge {severity}">{severity}</span><br>
            <small>Tool: {tool} | URL: {url}</small><br>
            <p>{desc}</p>
        </div>
"""
    
    def _severity_order(self, severity: str) -> int:
        order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
        return order.get(severity, 5)
    
    def _basic_summary(self, findings, risk_score: float) -> str:
        return f"This vulnerability assessment identified {len(findings)} findings with an overall risk score of {risk_score:.1f}/10."
    
    def _generate_recommendations(self, findings) -> str:
        recs = "### Priority Actions\n\n"
        critical_high = [f for f in findings if getattr(f, 'severity', '') in ["CRITICAL", "HIGH"]]
        for f in critical_high[:5]:
            recs += f"- **{getattr(f, 'name', 'Unknown')}**: Review and remediate\n"
        return recs


def generate_report(memory, output_dir: Path = None, formats = None) -> dict:
    if output_dir is None:
        output_dir = Path("/app/output")
    output_dir.mkdir(exist_ok=True, parents=True)
    
    if formats is None:
        formats = ["markdown", "json", "html"]
    
    generator = ReportGenerator(memory)
    results = {}
    
    if "markdown" in formats:
        md_path = output_dir / f"{memory.scan_id}_report.md"
        results["markdown"] = str(md_path)
        generator.generate_markdown(md_path)
    
    if "json" in formats:
        json_path = output_dir / f"{memory.scan_id}_report.json"
        results["json"] = str(json_path)
        generator.generate_json(json_path)
    
    if "html" in formats:
        html_path = output_dir / f"{memory.scan_id}_report.html"
        results["html"] = str(html_path)
        generator.generate_html(html_path)
    
    return results
